# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Alter
version:      0.01
version_from: lib/File/Alter.pm
installdirs:  site
requires:
    IO::File:                      0
    IO::String:                    0
    Params::Check:                 0.23
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
